swagger: '2.0'
info:
  version: 1.1.1
  title: DEA System API
paths:
  # root resource path entity must match the file name or the documentation will not get attached to the right API Gateweay resource
  # (e.g. openapi-auth.yml must only contain '/auth' and all child APIs)
  /system/audit:
    post:
      summary: Generates audit log for System
      operationId: requestSystemAudit
      tags:
        - elevated
      parameters:
        - in: body
          name: Audit payload
          required: false
          schema:
            $ref: '#/definitions/AuditPayload'
      responses:
        '200':
          description: Audit Query ID
          schema:
            type: object
            properties:
              auditId:
                type: string
  /system/audit/{auditId}/csv:
    get:
      summary: Returns audit log for system
      operationId: getSystemAudit
      tags:
        - elevated
      parameters:
        - name: auditId
          in: path
          description: Audit log ID
          required: true
          type: string
      responses:
        '200':
          description: Audit log CSV result and status
          schema:
            $ref: '#/definitions/AuditResult'

definitions:
  AuditResult:
    type: object
    properties:
      status:
        type: string
        items:
          $ref: '#/definitions/QueryStatus'
      downloadUrl:
        type: string
  AuditPayload:
    type: object
    properties:
      from:
        type: number
      to:
        type: number
  QueryStatus:
    type: string
    enum: [Cancelled, Complete, Failed, Running, Scheduled, Timeout, Unknown]
