swagger: '2.0'
info:
  version: 1.1.1
  title: DEA User API
paths:
  # root resource path entity must match the file name or the documentation will not get attached to the right API Gateweay resource
  # (e.g. openapi-auth.yml must only contain '/auth' and all child APIs)
  /users:
    get:
      summary: Get all users
      tags:
        - cases
      parameters:
        - in: query
          name: limit
          type: integer
        - in: query
          name: next
          type: string
      responses:
        200:
          description: Success Response
          schema:
            type: object
            properties:
              users:
                type: array
                items:
                  $ref: '#/definitions/Users'
              next:
                type: string
  /users/{userId}/audit:
    post:
      summary: Generates audit log for User
      operationId: requestUserAudit
      tags:
        - elevated
      parameters:
        - name: userId
          in: path
          description: User ID to generate audit log for
          required: true
          type: string
        - in: body
          name: Audit payload
          required: false
          schema:
            $ref: '#/definitions/AuditPayload'
      responses:
        '200':
          description: Audit Query ID
          schema:
            type: object
            properties:
              auditId:
                type: string
  /users/{userId}/audit/{auditId}/csv:
    get:
      summary: Returns audit log for a User
      operationId: getUserAudit
      tags:
        - elevated
      parameters:
        - name: userId
          in: path
          description: User ID to return audit log entries for
          required: true
          type: string
        - name: auditId
          in: path
          description: Audit log ID
          required: true
          type: string
      responses:
        '200':
          description: Audit log CSV result and status
          schema:
            $ref: '#/definitions/AuditResult'

definitions:
  AuditResult:
    type: object
    properties:
      status:
        type: string
        items:
          $ref: '#/definitions/QueryStatus'
      downloadUrl:
        type: string
  AuditPayload:
    type: object
    properties:
      from:
        type: number
      to:
        type: number
  QueryStatus:
    type: string
    enum: [Cancelled, Complete, Failed, Running, Scheduled, Timeout, Unknown]
  User:
    type: object
    required:
      - ulid
      - firstName
      - lastName
      - lowerFirstName
      - lowerLastName
    properties:
      ulid:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      lowerFirstName:
        type: string
      lowerLastName:
        type: string
  Users:
    type: array
    required:
      - users
    items:
      $ref: '#/definitions/User'

