swagger: '2.0'
info:
  version: 1.1.1
  title: DEA Available Endpoints API
paths:
  /availableEndpoints:
    get:
      summary: Get available endpoints for a user
      tags:
        - cases
      responses:
        200:
          description: Success Response
          schema:
            type: object
            properties:
              endpoints:
                type: array
                items:
                  type: string

