openapi: '3.0.0'
info:
  version: 1.1.1
  title: DEA Available Endpoints API
paths:
  # root resource path entity must match the file name or the documentation will not get attached to the right API Gateweay resource
  # (e.g. openapi-auth.yml must only contain '/auth' and all child APIs)
  /available-endpoints:
    get:
      summary: Get available endpoints for a user
      tags:
        - cases
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      type: string
