# Stage Name
stage: demo
awsRegion: us-west-2
awsRegionShortName: sea
apiUrlOutput: ''
rootUserEmail: bogus@bogus.com
allowedOrigins: ['http://localhost:3000']
cognitoDomain: 'test-dea-domain' # Must be globally unique
websiteUrl: 'http://localhost:3000'
userPoolId: 'us-east-2_111111'
clientId: '313123123123'
clientSecret: '123123123123123123'
