stage: dev # Stage Name
awsRegion: us-east-1
awsRegionShortName: va #two or three letter abbreviation for the region. You can choose your own abbreviation
isTestingEnv: true #set to true if you plan to run end to end tests in this deployment
allowedOrigins: ["http://localhost:3000"] # DEA API will allow this domains to make requests.
cognitoDomain: 'amuthana-dea-dev-iad' # Must be globally unique
websiteUrl: 'http://localhost:3000'

# Used for end to end testing; grab them from Cognito console after cdk-deploy completes.
userPoolId: 'us-east-1_vv6g8ImCF'
clientId: '2lhc8deao7pnn8hrit04deej3n'
identityPoolId: 'us-east-1:ade87c17-fc7f-42a5-8c58-18143f727ce4'
apiUrlOutput: 'https://mzu75ldq8f.execute-api.us-east-1.amazonaws.com/dev/'

# api url output and stack website url
stacks:
  - name: 'dea-iad'
    WebsiteURL: 'https://mzu75ldq8f.execute-api.us-east-1.amazonaws.com/dev/'
