#stage: dev # Stage Name
#awsRegion: us-east-1
#awsRegionShortName: va #two or three letter abbreviation for the region. You can choose your own abbreviation
#rootUserEmail: user@example.com    # DEA will automatically create this Cognito user for you.
#allowedOrigins: ["http://localhost:3000"] # DEA API will allow this domains to make requests.
#cognitoDomain: 'user-test' # Must be globally unique
#websiteUrl: 'http://localhost:3000'

# Used for local Lambda development; grab them from Cognito console after cdk-deploy completes.
# Once values are entered, re-run cdk-deploy.
#userPoolId: ''
#clientId: ''
#clientSecret: ''

# api url output and stack website url
# apiUrlOutput: ''
# stacks:
#  - name: ''
#    WebsiteURL: ''
