#stage: dev # Stage Name
#awsRegion: us-east-1
#awsRegionShortName: va #two or three letter abbreviation for the region. You can choose your own abbreviation
#isTestingEnv: true #set to true if you plan to run end to end tests in this deployment
#allowedOrigins: ["http://localhost:3000"] # DEA API will allow this domains to make requests.
#cognitoDomain: 'user-test' # Must be globally unique
#websiteUrl: 'http://localhost:3000'

# Used for end to end testing; grab them from Cognito console after cdk-deploy completes.
#userPoolId: ''
#clientId can be found in Cognito console -> App integration tab -> scroll to bottom -> App client list section
#clientId: ''
#identityPoolId: ''
#apiUrlOutput: ''

# api url output and stack website url
# apiUrlOutput: ''
# stacks:
#  - name: ''
#    WebsiteURL: ''
