stage: test
awsRegionShortName: testville
awsRegion: us-east-1
isTestingEnv: true
rootUserEmail: test@bogus.oof
allowedOrigins: ['test']
userPoolId: 'kiddiepool'
clientId: 'clientidtest'
clientSecret: 'shh'
apiUrlOutput: 'https://bogus.bogus'
stacks:
  - name: teststack
    WebsiteURL: 'https://bogus.bogus'
